#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

for dir in ./*/*
do
	echo -en "Cleaning ${dir} : "
  if make -C ${dir} fclean > /dev/null 2>&1; then
		echo -e "${GREEN}Cleaned ${dir}${NC}"
	else
		echo -e "${RED}Failed to clean ${dir}${NC}"
  fi
done