on: [ push, pull_request ]

jobs:
    pushing-vogsphere:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}

            -   name: Clone libftTester
                uses: actions/checkout@v2
                with:
                    repository: Tripouille/libftTester
                    path: circle_0/_libft/libftTester

            -   name: Testing libft
                run : |
                    cd circle_0/_libft
                    ls -a
                    cd libftTester
                    ls -a
                    make m = launch mandatory tests

            -   name: Saving all changes
                run : |
                    git config --global user.email matisse.chenavas@gmail.com
                    git config --global user.name mchenava
                    make save-all
