on: [ push, pull_request ]

jobs:
    pushing-vogsphere:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}

            -   name: Saving all changes
                run : |
                    git config --global user.email matisse.chenavas@gmail.com
                    git config --global user.name mchenava
                    make save-all

            -   name: Clone libftTester
                uses: actions/checkout@v2
                with:
                    repository: Tripouille/libftTester
                    path: circle_0/_libft/libftTester

            -   name: Testing libft
                run : |
                    export error_found=0
                    cd circle_0/_libft
                    export funcnames=$(find ../ -type f -name "*.c" -print0 | xargs -I {} -0 -n1 bash -c "echo {} | rev | cut -c3- | rev | sed 's#../ft_##'")
                    cd libftTester
                    for funcname in $funcnames; do
                        output=$(make $funcname)
                        echo "$(echo "$output" | grep OK)"
                        kos=$(echo "$output" | sed 's/KO you//g' | grep KO)
                        if [[ "$kos" != "" ]]; then echo "$kos"; error_found=1; fi
                    done
                    exit error_found
                    cat Makefile
                    make m = launch mandatory tests

