on: [ push, pull_request ]

jobs:
    pushing-vogsphere:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup key
                uses: shimataro/ssh-key-action@v2
                with:
                    key: ${{ secrets.SSH_PRIVATE_KEY }}
                    known_hosts: ${{ secrets.KNOWN_HOSTS }}
            -   name: Saving all changes
                run : make save-all
