on: [ push, pull_request ]

jobs:
    pushing-vogsphere:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   name: Setup key
                uses: ZEDIUM-Off/ssh-agent-42Lyon@master
                with:
                    ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            -   run: make save-all
